### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2est#161]
https://github.com/nlmixr2/nlmixr2est/compare/5b2f49d06fc2e6fd749c47c396f4da235f2a41bd...main

**Comment by billdenney** [comment]
Why does inner.cpp line 1121 use "+=" while line 1170 uses "-="?

https://github.com/nlmixr2/nlmixr2est/blob/145673a74d31219889a6e77fa84feaefa22cb3c4/src/inner.cpp#L1121-L1170

(The same is true in saem, so I'm guessing it's intentional, but I'm not sure why it is:

https://github.com/nlmixr2/nlmixr2est/blob/145673a74d31219889a6e77fa84feaefa22cb3c4/src/saem.cpp#L1852-L1861

)

**Comment by billdenney** [comment]
I think that is my only code review finding, and I'm pretty sure that it just is asking for a comment in the code to make it a bit clearer what's happening.

I wonder if it may make sense to simplify the code overall to a generalized likelihood function with censoring function.  I think that may even already exist in the `doCens()` function in saem.cpp.  The general idea would be to take the following as inputs:

* observed value
* is censored? (yes/no)
* lower limit
* upper limit
* mean estimate
* sd estimate
* probability distribution function
* cumulative distribution function

And, it returns the vector of likelihoods.  It would have to handle 4 states:

* observed value (not censored)
* censored below a given value
* censored above a given value
* interval censored (between two values)

And maybe, we make a wrapper for the M2 method, too.

I suggest this because it looks like we have censoring in a couple of different places.  If/when we add more estimation methods, it seems like it would be better to have one core censoring code location.

**Comment by mattfidler** [comment]
Maybe Im wrong here, but I think we covered all of the censoring methods that make sense, right?

Im not saying refactoring couldnt be useful but ai am saying that we are not likely to add any others.

**Comment by mattfidler** [comment]
Also Im not sure what you have makes sense to me.  Maybe we can discuss later.

**Comment by mattfidler** [comment]
Thanks @billdenney 

I will see about refactoring to have a cross-method censoring implementation
