### ISSUE TITLE
For discussion (maybe a feature request, maybe not): `vcov()` gives a different set of estimated parameters than `fixef()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#291]
When I run `vcov()` on a model, it gives the estimated fixed-effect parameters without the residual error parameters.

When I run `fixef()` on a model, it gives all parameters including parameters that were fixed.

I would have guessed that the same parameters would be provided for both.  I like that `fixef()` gives all parameters, so is it possible to set the variance for fixed parameters in `vcov()` to zero?

(I can give a reprex, if helpful.)

**Comment by mattfidler** [comment]
To me, this is what should be done.  `vcov()` giving `0` for fixed parameters may not be actually correct.  It is likely they have a high variability and cannot be estimated, so setting these to `0` is not correct and may be confusing to some.

I believe it matches what `nlme` does too (though I haven't tested this recently). Since `vcov` comes from `nlme` matching the behavior makes sense to me.

I think if we expand the variance-covariance matrix to include error parameters the should also be in here.

Just my opinion.

One other gotcha is this may (or may not) be used for `tidy` and `glance` models.

**Comment by billdenney** [comment]
Thanks for the thoughts.  They make sense to me.  Closing.
