### ISSUE TITLE
R crash with saem estimation and window size change

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#361]
I have tried to make a reprex for this without success.

When I'm running nlmixr2 with saem estimation in Rstudio, and I change the window size, the R session sometimes crashes.  My guess is that it has something to do with the printing code expecting a certain screen width and the screen width changing, but I'm not sure.

I tried reproducing this on Linux, but I don't think that changing the window size immediately changes the printing width, so I can't reproduce it there (and therefore can't get a back trace).  It doesn't seem to have anything to do with the model itself (it happens with different models).

If this issue is too vague, feel free to close it.

**Comment by mattfidler** [comment]
There is no code about window size for `saem`.  I'm unsure why it is crashing.

My hypothesis but likely it is because it is forcing an interrupt of the parallel process in R.  

While I take pains that interrupt is not allowed during parallel processing, there could be some small code in R itself that  allows changing window size which sends an interrupt code, which then crashes R since it is running a parallel ODE solving process.

If the interrupt is in R itself I cannot do anything.  I also cannot do anything if I cannot find where the interrupt is occuring.

So... unfortunately, for now I will probably close this, and keep it in mind.

**Comment by mattfidler** [comment]
It would also apply to `rxode2` running a large system in parallel (if you want to test the hypothesis).

I will probably be moving the code to RcppParallel eventually which may mean that this may have a different outcome anyhow.
